### PR TITLE
Change constant v type

### PR DESCRIPTION
**Pull request by kettlebell**
For issue #343.

In summary, I've split out a `Literal` type to replace `Value` in `Constant::v`. Also `DataSerializer` was changed to serialise/parse `Literal` instead of `Value`.

### CODE REVIEW

**Review by greenhat — CHANGES_REQUESTED** [review]
Looking great! Please remove JS error conversion (from earlier PRs).

**Comment by kettlebell** [comment]
Really sorry about the first 2 commits. I'm trying to figure out how to rebase (first time for me) but can't seem to undo that merge. As a last resort I'll make a new PR with the last 3 commits unchanged.

**Comment by greenhat** [comment]
> Really sorry about the first 2 commits. I'm trying to figure out how to rebase (first time for me) but can't seem to undo that merge. As a last resort I'll make a new PR with the last 3 commits unchanged.

No worries! Try interactive rebase and skip/delete that merge commit. See https://stackoverflow.com/questions/12604824/how-do-i-rebase-while-skipping-a-particular-commit

**Comment by kettlebell** [comment]
Thanks for the help, I did use the interactive mode but wasn't able to 'drop' that merge commit. But I've messed things up it seems. I'll start again from the head of `develop`. Sorry again for the troubles.

**Comment by greenhat** [comment]
Hey! It's no big deal! I struggle with git pretty often. No worries!

**Pull request closed without merging**
