### PR TITLE
Add `FullBlock` to `ergo-lib`

### PR DESCRIPTION
**Pull request by kettlebell**

### CODE REVIEW

**Review by greenhat — CHANGES_REQUESTED** [review]
Looking good! Thank you! 
Would I be able to parse it from JSON? I'm seeing `blockTransactions` field name in JSON, while here it's `block_transactions`. 

Could you please fix the build wo default features?

**Comment by greenhat** [comment]
Oh, and I fixed the test coverage CI job in develop. Please, rebase.

**Comment by kettlebell** [comment]
> Looking good! Thank you! Would I be able to parse it from JSON? I'm seeing `blockTransactions` field name in JSON, while here it's `block_transactions`.
> 
> Could you please fix the build wo default features?

Thanks for the find, I've fixed the field name. It slipped through because we don't use `blocks/{headerId}` endpoint directly to create `FullBlock`. All issues fixed plus added JSON roundtrip test.

**Review by greenhat — APPROVED** [review]
Looking great! Thank you, I appreciate the added test!

**Pull request merged**
