### PR TITLE
Replace instances of `Rc<ErgoBox>` with `Arc<ErgoBox>`

### LINKED ISSUE #661: Replace instances of `Rc<ErgoBox>` with `Box<ErgoBox>`
Allows `Transaction` and other types to be `Send`, so we can pass it between threads.

### PR DESCRIPTION
**Pull request by kettlebell**
Close #661

### CODE REVIEW

**Review by oskin1 — APPROVED** [review]

**Review by greenhat — CHANGES_REQUESTED** [review]
Looking good! I'm thrilled to see sigma-rust in a multi-threaded environment!
Have you considered thread-safe `Arc` instead of `Box`? I recall the reason for `Rc` was that ergo boxes have quite a big memory footprint, so I aimed to eventually eliminate all `.clone()` calls and use references as much as possible for ergo boxes. Although `Box` is also a reference, but only for single ownership, which I'm feeling is not enough for ergo boxes (think txs, context in the interpreter, etc.).

**Comment by kettlebell** [comment]
> Looking good! I'm thrilled to see sigma-rust in a multi-threaded environment! Have you considered thread-safe `Arc` instead of `Box`? I recall the reason for `Rc` was that ergo boxes have quite a big memory footprint, so I aimed to eventually eliminate all `.clone()` calls and use references as much as possible for ergo boxes. Although `Box` is also a reference, but only for single ownership, which I'm feeling is not enough for ergo boxes (think txs, context in the interpreter, etc.).

Yes, I did consider it. I had a look at how `Rc<ErgoBox>` was used throughout the codebase and nothing jumped out at me in terms of shared ownership. I chose to use `Box` because I know that `Arc` imposes extra runtime cost over `Rc`. I'm happy to change it over to `Arc`, no problem at all.

**Comment by greenhat** [comment]
> Yes, I did consider it. I had a look at how `Rc<ErgoBox>` was used throughout the codebase and nothing jumped out at me in terms of shared ownership. I chose to use `Box` because I know that `Arc` imposes extra runtime cost over `Rc`. I'm happy to change it over to `Arc`, no problem at all.

Thank you! My bad. There are way too many `.clone()` calls still there but I hope to get rid of them eventually.

**Review by greenhat — APPROVED** [review]
Thank you!

**Comment by oskin1** [comment]
@greenhat isn't adding Arc inside ErgoBox too opinionated solution? Whoever wanting to share ownership of ErgoBox can wrap it into Arc in whole.

**Comment by greenhat** [comment]
> @greenhat isn't adding Arc inside ErgoBox too opinionated solution? Those who want to share ownership of ErgoBox can wrap it into Arc in whole.

I'm not sure I understand what you mean by "Arc inside ErgoBox". 
The `Rc` (changed in this PR) was used in the interpreter `Context` type. In the future, I'd like not to clone ErgoBox but pass a reference and share the ownership between tx, context, etc.

**Comment by greenhat** [comment]
My aim is to share the ownership to the ref to the ErgoBox. The ErgoBox itself owns it's data and there is no references used for it's internal parts.

**Comment by oskin1** [comment]
@greenhat My bad, I misunderstood how CBox relates to ErgoBox.

**Pull request merged**
