### PR TITLE
Add very partial implementation of THRESHOLD connective

### PR DESCRIPTION
**Pull request by Shimuuar**
Implementation only goes as far a to allow successful roundtrip for transaction recorder on blockchain.

### CODE REVIEW

**Comment by greenhat** [comment]
@Shimuuar Please be aware that this op code is used for both 

IR node `AtLeast` https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/trees.scala#L431-L453

**AND**

SigmaBoolean type `CTHRESHOLD` used in sigma protocols.
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/trees.scala#L120-L129 which you can encounter on the chain if it's used in constants. 

I don't recall we used `CTHRESHOLD` constant anywhere. Are you sure it's not `AtLeast` IR node?

**Comment by Shimuuar** [comment]
Naturally I'm not sure. I'll track down offending transactions (there're 3 of them) but AFAIR error messages led me to sigma-expressions.

**Comment by Shimuuar** [comment]
Yes it seems that in this case it's serialization of the `SigmaBoolean`. Easiest way to find out what's going on is to panic at non-implemented code and look at backtrace. Here it is 

```
   0: std::panicking::begin_panic
   1: ergotree_ir::serialization::sigmaboolean::<impl ergotree_ir::serialization::serializable::SigmaSerializable for ergotree_ir::sigma_protocol::sigma_boolean::SigmaBoolean>::sigma_parse
   2: ergotree_ir::serialization::data::DataSerializer::sigma_parse
   3: ergotree_ir::serialization::constant::<impl ergotree_ir::mir::constant::Constant>::parse_with_type_code
   4: ergotree_ir::serialization::expr::<impl ergotree_ir::mir::expr::Expr>::parse_with_tag
   5: ergotree_ir::serialization::expr::<impl ergotree_ir::serialization::serializable::SigmaSerializable for ergotree_ir::mir::expr::Expr>::sigma_parse
   6: <ergotree_ir::ergo_tree::ErgoTree as ergotree_ir::serialization::serializable::SigmaSerializable>::sigma_parse
   7: ergo_lib::chain::ergo_box::parse_box_with_indexed_digests
```

In that transaction sigma expression is stored as a constant

**Comment by greenhat** [comment]
> Yes it seems that in this case it's serialization of the `SigmaBoolean`. Easiest way to find out what's going on is to panic at non-implemented code and look at backtrace. Here it is
> 
> ```
>    0: std::panicking::begin_panic
>    1: ergotree_ir::serialization::sigmaboolean::<impl ergotree_ir::serialization::serializable::SigmaSerializable for ergotree_ir::sigma_protocol::sigma_boolean::SigmaBoolean>::sigma_parse
>    2: ergotree_ir::serialization::data::DataSerializer::sigma_parse
>    3: ergotree_ir::serialization::constant::<impl ergotree_ir::mir::constant::Constant>::parse_with_type_code
>    4: ergotree_ir::serialization::expr::<impl ergotree_ir::mir::expr::Expr>::parse_with_tag
>    5: ergotree_ir::serialization::expr::<impl ergotree_ir::serialization::serializable::SigmaSerializable for ergotree_ir::mir::expr::Expr>::sigma_parse
>    6: <ergotree_ir::ergo_tree::ErgoTree as ergotree_ir::serialization::serializable::SigmaSerializable>::sigma_parse
>    7: ergo_lib::chain::ergo_box::parse_box_with_indexed_digests
> ```
> 
> In that transaction sigma expression is stored as a constant

Yes, I agree, it's a constant.

**Comment by greenhat** [comment]
Hey! I'm adding Diffie-Hellman tuple support to sigma protocol in https://github.com/ergoplatform/sigma-rust/pull/315 and since you changed the same files I expect some merge conflict along the way. Would you like to merge this PR as is and I'll resolve merge conflicts in my branch/PR?

**Comment by Shimuuar** [comment]
Yes, if you fine with merging this PR as it is. I don’t think I can improve it further

**Review by greenhat — APPROVED** [review]

**Pull request merged**
