### PR TITLE
Run ergo-lib-wasm JS tests in a headless browser

### PR DESCRIPTION
**Pull request by hanbu97**
job step: 
```
 - name: run JS browser tests
   run: |
     wasm-pack build
     npm install
     npm run test-browser
```

For browser only tests, just put test file in ergo-lib-wasm/tests_browser folder. Tests in ergo-lib-wasm/tests folder can be run in both js tests and js browser tests.

### CODE REVIEW

**Comment by greenhat** [comment]
Thank you for your contribution!

> job step:
> 
> ```
>  - name: run JS browser tests
>    run: |
>      wasm-pack build
>      npm install
>      npm run test-browser
> ```

Could you please split `js_test` job in ci.yml into `browser_js_test` and `node_js_test` and add the step above to the browser part?
 
> 
> For browser only tests, just put test file in ergo-lib-wasm/tests_browser folder. Tests in ergo-lib-wasm/tests folder can be run in both js tests and js browser tests.

It'd be great if you could add this explanation to `ergo-lib-wasm/README.md`.

**Comment by hanbu97** [comment]
> Thank you for your contribution!
> 
> > job step:
> > ```
> >  - name: run JS browser tests
> >    run: |
> >      wasm-pack build
> >      npm install
> >      npm run test-browser
> > ```
> 
> Could you please split `js_test` job in ci.yml into `browser_js_test` and `node_js_test` and add the step above to the browser part?
> 
> > For browser only tests, just put test file in ergo-lib-wasm/tests_browser folder. Tests in ergo-lib-wasm/tests folder can be run in both js tests and js browser tests.
> 
> It'd be great if you could add this explanation to `eIrgo-lib-wasm/README.md`.

It's done. Please check it.

**Review by greenhat — CHANGES_REQUESTED** [review]
Looking great! Thank you!
Please, remove commented-out old imports in tests.

**Comment by hanbu97** [comment]
Ok, all cleared.

**Review by greenhat — APPROVED** [review]
Great! Thank you!

**Comment by greenhat** [comment]
Please contact me (greenhat) on our Discord https://discord.gg/kj7s7nb for receiving your bounty. Please post your Discord username in a comment to this PR for identity confirmation.

**Pull request merged**
